package br.model;

// Generated 16/09/2014 16:15:30 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Filial generated by hbm2java
 */
@Entity
@Table(name = "Filial", catalog = "VoceAluga")
public class Filial implements java.io.Serializable
{

	private String filialOid;
	private Pessoa pessoa;
	private String descricao;
	private Set manutencaos = new HashSet(0);

	public Filial()
	{
	}

	public Filial(String filialOid, Pessoa pessoa, String descricao)
	{
		this.filialOid = filialOid;
		this.pessoa = pessoa;
		this.descricao = descricao;
	}

	public Filial(String filialOid, Pessoa pessoa, String descricao,
			Set manutencaos)
	{
		this.filialOid = filialOid;
		this.pessoa = pessoa;
		this.descricao = descricao;
		this.manutencaos = manutencaos;
	}

	@Id
	@Column(name = "filial_oid", unique = true, nullable = false, length = 45)
	public String getFilialOid()
	{
		return this.filialOid;
	}

	public void setFilialOid(String filialOid)
	{
		this.filialOid = filialOid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pessoa_oid", nullable = false)
	public Pessoa getPessoa()
	{
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa)
	{
		this.pessoa = pessoa;
	}

	@Column(name = "descricao", nullable = false)
	public String getDescricao()
	{
		return this.descricao;
	}

	public void setDescricao(String descricao)
	{
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
	public Set getManutencaos()
	{
		return this.manutencaos;
	}

	public void setManutencaos(Set manutencaos)
	{
		this.manutencaos = manutencaos;
	}

}
