package br.model;

// Generated 16/09/2014 16:15:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GrupoCarro generated by hbm2java
 */
@Entity
@Table(name = "GrupoCarro", catalog = "VoceAluga")
public class GrupoCarro implements java.io.Serializable
{

	private int grupoCarroOid;
	private Integer total;
	private Integer disponiveis;
	private String descricao;

	public GrupoCarro()
	{
	}

	public GrupoCarro(int grupoCarroOid, String descricao)
	{
		this.grupoCarroOid = grupoCarroOid;
		this.descricao = descricao;
	}

	public GrupoCarro(int grupoCarroOid, Integer total, Integer disponiveis,
			String descricao)
	{
		this.grupoCarroOid = grupoCarroOid;
		this.total = total;
		this.disponiveis = disponiveis;
		this.descricao = descricao;
	}

	@Id
	@Column(name = "grupoCarro_oid", unique = true, nullable = false)
	public int getGrupoCarroOid()
	{
		return this.grupoCarroOid;
	}

	public void setGrupoCarroOid(int grupoCarroOid)
	{
		this.grupoCarroOid = grupoCarroOid;
	}

	@Column(name = "total")
	public Integer getTotal()
	{
		return this.total;
	}

	public void setTotal(Integer total)
	{
		this.total = total;
	}

	@Column(name = "disponiveis")
	public Integer getDisponiveis()
	{
		return this.disponiveis;
	}

	public void setDisponiveis(Integer disponiveis)
	{
		this.disponiveis = disponiveis;
	}

	@Column(name = "descricao", nullable = false, length = 45)
	public String getDescricao()
	{
		return this.descricao;
	}

	public void setDescricao(String descricao)
	{
		this.descricao = descricao;
	}

}
