package br.model;

// Generated 16/09/2014 16:15:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Manutencao generated by hbm2java
 */
@Entity
@Table(name = "Manutencao", catalog = "VoceAluga")
public class Manutencao implements java.io.Serializable
{

	private String manutencaoOid;
	private Filial filial;
	private Carro carro;

	public Manutencao()
	{
	}

	public Manutencao(String manutencaoOid, Filial filial, Carro carro)
	{
		this.manutencaoOid = manutencaoOid;
		this.filial = filial;
		this.carro = carro;
	}

	@Id
	@Column(name = "manutencao_oid", unique = true, nullable = false, length = 45)
	public String getManutencaoOid()
	{
		return this.manutencaoOid;
	}

	public void setManutencaoOid(String manutencaoOid)
	{
		this.manutencaoOid = manutencaoOid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "filal_oid", nullable = false)
	public Filial getFilial()
	{
		return this.filial;
	}

	public void setFilial(Filial filial)
	{
		this.filial = filial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "carro_oid", nullable = false)
	public Carro getCarro()
	{
		return this.carro;
	}

	public void setCarro(Carro carro)
	{
		this.carro = carro;
	}

}
