package br.model;

// Generated 30/11/2014 11:48:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Aluguel generated by hbm2java
 */
@Entity
@Table(name = "Aluguel", catalog = "VoceAluga")
public class Aluguel implements java.io.Serializable
{

	private String aluguelOid;
	private Pessoa pessoa;
	private Carro carro;
	private Reserva reserva;
	private Date dataInicio;
	private Date dataFim;
	private boolean pago;

	public Aluguel()
	{
	}

	public Aluguel(Pessoa pessoa, Carro carro,
			Reserva reserva, Date dataInicio, Date dataFim, boolean pago)
	{
		this.pessoa = pessoa;
		this.carro = carro;
		this.reserva = reserva;
		this.dataInicio = dataInicio;
		this.dataFim = dataFim;
		this.pago = pago;
	}

	@Id
	@Column(name = "aluguel_oid", unique = true, nullable = false, length = 45)
	public String getAluguelOid()
	{
		return this.aluguelOid;
	}

	public void setAluguelOid(String aluguelOid)
	{
		this.aluguelOid = aluguelOid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pessoa_oid", nullable = false)
	public Pessoa getPessoa()
	{
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa)
	{
		this.pessoa = pessoa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "carro_oid", nullable = false)
	public Carro getCarro()
	{
		return this.carro;
	}

	public void setCarro(Carro carro)
	{
		this.carro = carro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reserva_oid", nullable = false)
	public Reserva getReserva()
	{
		return this.reserva;
	}

	public void setReserva(Reserva reserva)
	{
		this.reserva = reserva;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataInicio", nullable = false, length = 10)
	public Date getDataInicio()
	{
		return this.dataInicio;
	}

	public void setDataInicio(Date dataInicio)
	{
		this.dataInicio = dataInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataFim", nullable = false, length = 10)
	public Date getDataFim()
	{
		return this.dataFim;
	}

	public void setDataFim(Date dataFim)
	{
		this.dataFim = dataFim;
	}

	@Column(name = "pago", nullable = false)
	public boolean isPago()
	{
		return this.pago;
	}

	public void setPago(boolean pago)
	{
		this.pago = pago;
	}

}
