package br.model;

// Generated 02/09/2014 10:58:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Carro generated by hbm2java
 */
@Entity
@Table(name = "Carro", catalog = "VoceAluga")
public class Carro implements java.io.Serializable
{

	private long carroOid;
	private String modelo;
	private String placa;
	private int ano;
	private Date ultimaManutencao;

	public Carro()
	{
	}

	public Carro(long carroOid, String modelo, String placa, int ano)
	{
		this.carroOid = carroOid;
		this.modelo = modelo;
		this.placa = placa;
		this.ano = ano;
	}

	public Carro(long carroOid, String modelo, String placa, int ano,
			Date ultimaManutencao)
	{
		this.carroOid = carroOid;
		this.modelo = modelo;
		this.placa = placa;
		this.ano = ano;
		this.ultimaManutencao = ultimaManutencao;
	}

	@Id
	@Column(name = "carro_oid", unique = true, nullable = false)
	public long getCarroOid()
	{
		return this.carroOid;
	}

	public void setCarroOid(long carroOid)
	{
		this.carroOid = carroOid;
	}

	@Column(name = "modelo", nullable = false, length = 45)
	public String getModelo()
	{
		return this.modelo;
	}

	public void setModelo(String modelo)
	{
		this.modelo = modelo;
	}

	@Column(name = "placa", nullable = false, length = 45)
	public String getPlaca()
	{
		return this.placa;
	}

	public void setPlaca(String placa)
	{
		this.placa = placa;
	}

	@Column(name = "ano", nullable = false)
	public int getAno()
	{
		return this.ano;
	}

	public void setAno(int ano)
	{
		this.ano = ano;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ultimaManutencao", length = 10)
	public Date getUltimaManutencao()
	{
		return this.ultimaManutencao;
	}

	public void setUltimaManutencao(Date ultimaManutencao)
	{
		this.ultimaManutencao = ultimaManutencao;
	}

}
