package br.model;

// Generated 24/11/2014 10:19:15 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Permissao generated by hbm2java
 */
@Entity
@Table(name = "Permissao", catalog = "VoceAluga")
public class Permissao implements java.io.Serializable
{

	private String permissaoOid;
	private String perfilOid;
	private String pessoaOid;

	public Permissao()
	{
	}

	public Permissao(String permissaoOid, String perfilOid, String pessoaOid)
	{
		this.permissaoOid = permissaoOid;
		this.perfilOid = perfilOid;
		this.pessoaOid = pessoaOid;
	}

	@Id
	@Column(name = "permissao_oid", unique = true, nullable = false, length = 45)
	public String getPermissaoOid()
	{
		return this.permissaoOid;
	}

	public void setPermissaoOid(String permissaoOid)
	{
		this.permissaoOid = permissaoOid;
	}

	@Column(name = "perfil_oid", nullable = false, length = 45)
	public String getPerfilOid()
	{
		return this.perfilOid;
	}

	public void setPerfilOid(String perfilOid)
	{
		this.perfilOid = perfilOid;
	}

	@Column(name = "pessoa_oid", nullable = false, length = 45)
	public String getPessoaOid()
	{
		return this.pessoaOid;
	}

	public void setPessoaOid(String pessoaOid)
	{
		this.pessoaOid = pessoaOid;
	}

}
