package br.model;

// Generated 02/09/2014 10:58:49 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name = "Pessoa", catalog = "VoceAluga")
public class Pessoa implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 2307353215778627493L;
	private int pessoaOid;
	private String nome;
	private String cpf;
	private String rg;
	private String carteira;
	private Character categoriaCarteira;
	private String telefone;
	private String email;

	public Pessoa()
	{
	}

	public Pessoa(int pessoaOid, String nome, String cpf, String rg)
	{
		this.pessoaOid = pessoaOid;
		this.nome = nome;
		this.cpf = cpf;
		this.rg = rg;
	}

	public Pessoa(int pessoaOid, String nome, String cpf, String rg,
			String carteira, Character categoriaCarteira, String telefone,
			String email)
	{
		this.pessoaOid = pessoaOid;
		this.nome = nome;
		this.cpf = cpf;
		this.rg = rg;
		this.carteira = carteira;
		this.categoriaCarteira = categoriaCarteira;
		this.telefone = telefone;
		this.email = email;
	}

	@Id
	@Column(name = "pessoa_oid", unique = true, nullable = false)
	public int getPessoaOid()
	{
		return this.pessoaOid;
	}

	public void setPessoaOid(int pessoaOid)
	{
		this.pessoaOid = pessoaOid;
	}

	@Column(name = "nome", nullable = false)
	public String getNome()
	{
		return this.nome;
	}

	public void setNome(String nome)
	{
		this.nome = nome;
	}

	@Column(name = "cpf", nullable = false, length = 12)
	public String getCpf()
	{
		return this.cpf;
	}

	public void setCpf(String cpf)
	{
		this.cpf = cpf;
	}

	@Column(name = "rg", nullable = false, length = 10)
	public String getRg()
	{
		return this.rg;
	}

	public void setRg(String rg)
	{
		this.rg = rg;
	}

	@Column(name = "carteira", length = 10)
	public String getCarteira()
	{
		return this.carteira;
	}

	public void setCarteira(String carteira)
	{
		this.carteira = carteira;
	}

	@Column(name = "categoriaCarteira", length = 1)
	public Character getCategoriaCarteira()
	{
		return this.categoriaCarteira;
	}

	public void setCategoriaCarteira(Character categoriaCarteira)
	{
		this.categoriaCarteira = categoriaCarteira;
	}

	@Column(name = "telefone", length = 8)
	public String getTelefone()
	{
		return this.telefone;
	}

	public void setTelefone(String telefone)
	{
		this.telefone = telefone;
	}

	@Column(name = "email", length = 45)
	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

}
