DROP TABLE Aluguel;
CREATE TABLE Aluguel (aluguel_oid varchar(45) NOT NULL, carro_oid varchar(45) NOT NULL, pessoa_oid varchar(45) NOT NULL, dataInicio date NOT NULL, dataFim date NOT NULL, pago bit NOT NULL, reserva_oid varchar(45) NOT NULL, formaPagamento varchar(45), PRIMARY KEY (aluguel_oid), INDEX fk_Aluguel_Carro_idx (carro_oid), INDEX fk_Aluguel_Pessoa_idx (pessoa_oid), INDEX fk_Aluguel_Reserva_idx (reserva_oid)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE Carro;
CREATE TABLE Carro (carro_oid varchar(45) NOT NULL, modelo varchar(45) NOT NULL, placa varchar(45) NOT NULL, ano int(4) NOT NULL, ultimaManutencao date, marca varchar(45) NOT NULL, disponivel varchar(45) NOT NULL, preco decimal(50,2), diaria decimal(50,2), vendido varchar(45) NOT NULL, formaPagamento varchar(45), PRIMARY KEY (carro_oid)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE Filial;
CREATE TABLE Filial (filial_oid varchar(45) NOT NULL, pessoa_oid varchar(45) NOT NULL, descricao varchar(255) NOT NULL, num_Filial int NOT NULL, PRIMARY KEY (filial_oid), INDEX fk_Filial_Gerente_idx (pessoa_oid)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE GrupoCarro;
CREATE TABLE GrupoCarro (grupoCarro_oid varchar(45) NOT NULL, total int, disponiveis int, descricao varchar(45) NOT NULL, PRIMARY KEY (grupoCarro_oid)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE ListaNegra;
CREATE TABLE ListaNegra (listaNegra_oid varchar(45) NOT NULL, pessoa_oid varchar(45) NOT NULL, justificativa varchar(300), PRIMARY KEY (listaNegra_oid), INDEX fk_ListaNegra_Pessoa_idx (pessoa_oid)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE Manutencao;
CREATE TABLE Manutencao (manutencao_oid varchar(45) NOT NULL, filal_oid varchar(45) NOT NULL, carro_oid varchar(45) NOT NULL, PRIMARY KEY (manutencao_oid), INDEX fk_Manutencao_Filial_idx (filal_oid), INDEX fk_Manutencao_Carro_idx (carro_oid)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE Perfil;
CREATE TABLE Perfil (perfil_oid varchar(45) NOT NULL, descricao varchar(255) NOT NULL, nome varchar(45) NOT NULL, PRIMARY KEY (perfil_oid)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE Permissao;
CREATE TABLE Permissao (permissao_oid varchar(45) NOT NULL, perfil_oid varchar(45) NOT NULL, pessoa_oid varchar(45) NOT NULL, PRIMARY KEY (permissao_oid)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE Pessoa;
CREATE TABLE Pessoa (pessoa_oid varchar(45) NOT NULL, nome varchar(255) NOT NULL, cpf varchar(12) NOT NULL, rg varchar(10) NOT NULL, carteira varchar(10), categoriaCarteira char(1), telefone varchar(8), email varchar(45), PRIMARY KEY (pessoa_oid), CONSTRAINT pessoa_oid_UNIQUE UNIQUE (pessoa_oid)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE Reserva;
CREATE TABLE Reserva (reserva_oid varchar(45) NOT NULL, pessoa_oid varchar(45) NOT NULL, carro_oid varchar(45) NOT NULL, dataInicio date NOT NULL, dataFim date NOT NULL, pagoAntecipado bit NOT NULL, PRIMARY KEY (reserva_oid), INDEX fk_Reserva_Pessoa_idx (pessoa_oid), INDEX fk_Reserva_Carro_idx (carro_oid)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE Aluguel ADD CONSTRAINT fk_Aluguel_Carro FOREIGN KEY (carro_oid) REFERENCES Carro (carro_oid) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Aluguel ADD CONSTRAINT fk_Aluguel_Pessoa FOREIGN KEY (pessoa_oid) REFERENCES Pessoa (pessoa_oid) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Aluguel ADD CONSTRAINT fk_Aluguel_Reserva FOREIGN KEY (reserva_oid) REFERENCES Reserva (reserva_oid) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Filial ADD CONSTRAINT fk_Filial_Gerente FOREIGN KEY (pessoa_oid) REFERENCES Pessoa (pessoa_oid) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE ListaNegra ADD CONSTRAINT fk_ListaNegra_Pessoa FOREIGN KEY (pessoa_oid) REFERENCES Pessoa (pessoa_oid) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Manutencao ADD CONSTRAINT fk_Manutencao_Carro FOREIGN KEY (carro_oid) REFERENCES Carro (carro_oid) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Manutencao ADD CONSTRAINT fk_Manutencao_Filial FOREIGN KEY (filal_oid) REFERENCES Filial (filial_oid) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Reserva ADD CONSTRAINT fk_Reserva_Carro FOREIGN KEY (carro_oid) REFERENCES Carro (carro_oid) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Reserva ADD CONSTRAINT fk_Reserva_Pessoa FOREIGN KEY (pessoa_oid) REFERENCES Pessoa (pessoa_oid) ON DELETE NO ACTION ON UPDATE NO ACTION;
